[package]
name = "nw"
description = "NetWarden CLI"
version = "0.1.0"
edition = "2024"

[dependencies]
tcping = { path = "../../libraries/tcping" }
netinfo = { path = "../../libraries/netinfo" }
probe = { path = "../../libraries/probe"}
geoip = { path = "../../libraries/geoip"}
anyhow = "1.0"
